### ISSUE TITLE
wordnet links

### ISSUE THREAD

**Issue by arademaker** [cu-clear/semlink#5]
Hi, in https://verbs.colorado.edu/semlink/, we have WN listed. But I didn't see the links to WN in this repo. Can you clarify? WN  was linked? What version?

**Comment by MarthaSPalmer** [comment]
If you hover over each class member you will see specific links, including to WN senses.  I don’t Demberg the version off the top of my head but that should be available somewhere.

Martha


On Jun 24, 2021, at 6:25 AM, Alexandre Rademaker ***@***.***> wrote:

﻿

Hi, in https://verbs.colorado.edu/semlink/, we have WN listed. But I didn't see the links to WN in this repo. Can you clarify? WN was linked? What version?

**Comment by arademaker** [comment]
Thank you @MarthaSPalmer , I found the links to WN in the VerbNet files (e.g. https://github.com/cu-clear/verbnet/blob/master/verbnet3.4/act-114.xml#L86)

**Comment by arademaker** [comment]
I will try to find the version of WN... What papers should I read to know about the construction of semlink?

**Comment by nschneid** [comment]
There's an IWCS paper: https://iwcs2021.github.io/proceedings/iwcs/pdf/2021.iwcs-1.21.pdf

**Comment by arademaker** [comment]
The main question of this issues was answered
