### ISSUE TITLE
PB-VN mappings have been re-broken

### ISSUE THREAD

**Issue by aaronstevenwhite** [cu-clear/semlink#6]
In March, I pointed out to @ghamzak in an email discussion that the PB-VN mapping were treated as one-to-one but that they must be one-to-many because the same PB roleset can map to distinct VN classes. [This commit](https://github.com/cu-clear/semlink/commit/ee478561a8252184d0df382951f3124ec552da8e) fixed the problem, but the error was reintroduced by [this commit](https://github.com/cu-clear/semlink/commit/99076a6d0cabbeb2c027bd3a4aae30ad3db62cf2) (@kevincstowe). I might suggest developing a JSON schema against which these mappings are validated prior to merging into master to avoid reintroducing this error in the future.

**Comment by kevincstowe** [comment]
Unfortunately the prior commit also deleted a bunch of the mappings, hence the error introducing fix. I've reworked the script so it now generates in a new format which captures the one-to-many mapping:

`{"accept.01": {"29.2-1-1": {"ARG0": "agent", "ARG1": "theme", "ARG3": "attribute"}, "77.1": {"ARG0": "agent", "ARG1": "theme"}, "13.5.2": {"ARG0": "agent", "ARG1": "theme", "ARG2": "source"}}}`

The keys remain the same. The value is a dictionary keyed by VN classes, with the values being the respective argument mappings. Personally I think this is a bit cleaner, but I'm also happy with the previous formatting, with the value being a list of dictionaries with "vn_class" and "args" attributes. Which would you prefer?

**Comment by aaronstevenwhite** [comment]
The above looks great. Thank you.

**Comment by kevincstowe** [comment]
Okay great, I've pushed those and updated the generator. We still need to look into some kind of validation to ensure everything's valid as you suggested, but for now these should be good.

**Comment by aaronstevenwhite** [comment]
Great. Thanks so much for the quick reply.
